prisma/dataguide

src/components/homePageHeader.tsx

Cleanup highlight a bit

---

src/components/newsletter/index.tsx

Adjust button

---

content/03-postgresql/07-create-and-delete-databases-and-tables.mdx
gatsby-node.js
plugins/gatsby-remark-check-links-numberless/index.js
plugins/gatsby-remark-to-absoluteurl/index.js
src/utils/algolia.js
src/utils/urlGenerator.ts

fix: all numbers being stripped from url

---

config.js
content/index.mdx

- siteUrl is currently wrong
- title, meta-title and meta-description could use some tweaking

chore(config): Fix siteUrl and update title, meta-title and -description

---

gatsby-browser.js
src/components/customMdx/authorInfo.tsx
src/components/customMdx/index.tsx

Usage: 
```
<AuthorInfo name="Diana Fey" image="https://imgur.com/5YEs4IC.png">
Dian didn’t exactly plan to drop out of college to specialize in SQL and backend development, but that’s how it happened. Fifteen years later, she’s designed databases supporting everything from industrial logistics and traceability systems to million-plus user social media games. She is the current maintainer of MassiveJS, an open source data mapper for Node.js focused on using PostgreSQL to the fullest.
</AuthorInfo>
```

feat: author info 

---

src/components/customMdx/footnote.tsx
src/components/customMdx/index.tsx
src/components/layout.css

#32 
Usage:
```
Some other text <footnote noteText="Towards a New Understanding of Data Modeling" noteLinkText="Software Development and Reality Construction" noteLink="link"> will learn how to send queries </footnote> and some more text
```

feat: footnotes

---

content/03-postgresql/07-create-and-delete-databases-and-tables.mdx

IF NOT EXISTS should be after CREATE TABLE.

Fix SQL syntax bug

---

src/components/header.tsx
src/components/layout.css

Added a header link to Prisma

---

content/01-intro/99-example.mdx
src/components/customMdx/code.tsx
static/_redirects

fix: code line num default + redirect file

---

src/components/pageBottom.tsx
src/layouts/articleLayout.tsx

feat: Edit on github

---

src/components/homePageHeader.tsx

fixes #4 even though it looks like it was fixed already, this makes a small adjustment to make the header even wider.

wider header

---

content/07-database-tools/02-evaluating-type-safety-in-the-top-8-typescript-orms.md

This code would throw a syntax error previously.

docs: fix quote in Dave's posts example

---

content/01-intro/99-example.mdx
gatsby-node.js
src/hooks/useAllArticlesQuery.ts

#95 
Usage 
```
skipBuild: true
```

feat: skipBuild option

---

package.json
src/components/layout.tsx
src/components/nextPrevious.tsx
src/layouts/articleLayout.tsx
yarn.lock

feat: Next and Previous links

---

content/04-postgresql/06-authentication-and-authorization/01-intro-to-authn-and-authz.mdx
content/04-postgresql/06-authentication-and-authorization/02-role-management.mdx
content/04-postgresql/06-authentication-and-authorization/index.mdx
content/05-mysql/03-authentication-and-authorization/04-role-management.mdx
content/05-mysql/03-authentication-and-authorization/index.mdx
src/components/seo.tsx
src/interfaces/Article.interface.ts
src/layouts/articleLayout.tsx
yarn.lock

Fixes https://github.com/prisma/dataguide/issues/119

Fix duplicate titles and descriptions

---

content/07-database-tools/01-top-11-nodejs-orms-query-builders-and-database-libraries.mdx
content/07-database-tools/02-evaluating-type-safety-in-the-top-8-typescript-orms.md
content/index.mdx

Update the node.js orm listicle for 2021

---

content/05-mysql/02-5-ways-to-host-mysql.mdx

This pull request adds a link to PlanetScale in the third party offerings for MySQL.

Add PlanetScale to Third Party Offerings

---

content/07-mssql/01-setting-up-a-local-sql-server-database.mdx

Add language around SQL server's password policy

---

src/components/socialShareSection.tsx

Modify social share text to point to correct account

---

content/01-intro/01-what-are-databases.mdx
content/04-postgresql/03-5-ways-to-host-postgresql.mdx
content/04-postgresql/04-setting-up-a-local-postgresql-database.mdx
content/04-postgresql/07-create-and-delete-databases-and-tables.mdx
content/04-postgresql/10-inserting-and-modifying-data/03-insert-on-conflict.mdx
content/04-postgresql/10-inserting-and-modifying-data/04-importing-and-exporting-data-in-postgresql.mdx
content/05-mysql/02-5-ways-to-host-mysql.mdx
content/06-sqlite/02-importing-and-exporting-data-in-sqlite.mdx
content/09-database-tools/01-top-11-nodejs-orms-query-builders-and-database-libraries.mdx

Second round of keyword assignments (title tags and meta descriptions) ready for review @etelsv @alex-emerich or @imchairmanm.

Seo Optimizations

---

src/components/banner.tsx
src/components/layout.tsx

feat: pdp banner

---

content/11-serverless/02-serverless-comparison.mdx

Update to New Serverless Article

---

content/11-serverless/01-what-is-serverless.mdx

Adjust SEO for intro to serverless article

---

content/08-mongodb/02-connecting-to-mongodb.mdx

This PR is for adding an FAQ section to the MDB connect to a database article

create mdb connect to database faq

---

content/04-postgresql/11-reading-and-querying-data/02-filtering-data.mdx

This PR is for adding an FAQ to the PSQL Filtering Data dataguide article

create a faq section for psql filtering article

---

content/04-postgresql/11-reading-and-querying-data/02-filtering-data.mdx
content/05-mysql/05-authentication-and-authorization/02-user-management-and-authentication.mdx

This PR is for the addition of an FAQ to the MySQL managing users article

Mysql users faq

---

content/05-mysql/12-short-guides/01-creating-deleting-users.mdx
content/index.mdx

PR for creating a short guide folder for MySQL and initial create/drop user guide

Short guide users mysql

---

authors.json
content/01-intro/01-what-are-databases.mdx
src/components/authorDetails.tsx
src/interfaces/Article.interface.ts
src/layouts/articleLayout.tsx

#224 
@imchairmanm The `authors.json` file is a sample one and you can replace the items with the right ones here. Also, please find the example usage in `content/01-intro/01-what-are-databases.mdx` : 
```
authors: ['nikolasburk', 'schickling']
```

feat: New Author component

---

content/04-postgresql/01-benefits-of-postgresql.mdx

Fixed missing `https://www.` part of urls

Fixed url to Postgre website

---

config.js

Revert "feat: Vercel prefix"

---

content/04-postgresql/11-date-types.mdx
content/08-mongodb/02-setting-up-a-local-mongodb-database.mdx
content/08-mongodb/05-configuring-mongodb-user-accounts-and-authentication.mdx
content/08-mongodb/06-authorization-and-privileges.mdx
content/08-mongodb/08-managing-documents.mdx
content/08-mongodb/11-mongodb-indexes.mdx
content/08-mongodb/12-mongodb-transactions.mdx
content/10-managing-databases/04-database-replication/01-database-replication-introduction.mdx
content/11-serverless/02-serverless-comparison.mdx
content/11-serverless/03-serverless-challenges.mdx

Resolves #266 
This PR resolves the conflicts in Public Accessory's other PR.  I don't have permission to push to that PR, but merging this one should do it.

Mkrasne2 meta improvements

---

content/04-postgresql/03-5-ways-to-host-postgresql.mdx

Hello.
Just to fix a little typo;
hf.

host postgresql: fix Database Labs typo

---

content/10-managing-databases/05-introduction-to-OLAP-OLTP.mdx
content/10-managing-databases/06-microservices-vs-monoliths.mdx
content/10-managing-databases/07-introduction-database-caching.mdx
content/10-managing-databases/08-testing-in-production.mdx
content/10-managing-databases/09-backup-considerations.mdx
content/10-managing-databases/10-intro-to-full-text-search.mdx
content/11-serverless/01-what-is-serverless.mdx
content/11-serverless/05-serverless-glossary.mdx
content/12-just-for-fun/01-us-most-popular-databases-by-states.mdx

Current link goes to a page that is instantly redirected, costing a few ms for each visitor.

fix: Replace /dataplatform link with correct /data-platform (to avoid redirects)

---

content/01-intro/04-database-glossary.mdx

Add query to glossary

---

package.json
plugins/gatsby-algolia-indexer/gatsby-config.js
plugins/gatsby-algolia-indexer/package.json

https://github.com/prisma/docs/pull/4497

fix: algolia partial indexing

---

src/components/layout.tsx
src/components/nextPrevious.tsx
src/components/pageBottom.tsx

- return home for homepage only
- Update link href

fix: Update page bottom

---

content/04-postgresql/01-benefits-of-postgresql.mdx
content/04-postgresql/02-getting-to-know-postgresql.mdx
content/04-postgresql/03-5-ways-to-host-postgresql.mdx
content/04-postgresql/04-setting-up-a-local-postgresql-database.mdx
content/04-postgresql/06-connecting-to-postgresql-databases.mdx
content/04-postgresql/13-reading-and-querying-data/04-optimizing-postgresql.mdx
content/04-postgresql/14-short-guides/04-exporting-schemas.mdx

Revert "update: docs redirected links"

---

content/04-postgresql/03-5-ways-to-host-postgresql.mdx

Add Neon to list of cloud providers and sort list alphabetically

Add Neon to cloud providers

---

src/components/sidebar/promo.tsx

Related to https://github.com/prisma/docs/pull/6020/files

Added msgs for Optimize

---

content/04-postgresql/03-5-ways-to-host-postgresql.mdx

fix: WEB-882 Remove 404 link from elephantsql

---

config.ts

fix: WEB-880 Remove algoliaAdminKey
